### PR TITLE
Feat/refactored

### PR DESCRIPTION
**Pull request by VoidRB**
A new beginning, on the same path.
Idek

### CODE REVIEW

**Comment by phr3nzy** [comment]
Let's also add linting, formatting and pre-commit checks (hint: oxlint + husky + lint-staged)

**Comment by VoidRB** [comment]
stupid question but why use these linters if deno can lint? are they just more detailed in how they lint?

**Comment by phr3nzy** [comment]
Didn't know Deno had linting, so we can use that instead of oxlint. The reason we use them is to catch bugs quickly and enforce some styling rules

**Comment by phr3nzy** [comment]
Let's aim to complete the refactor by incorporating the suggestions over the weekend. I still want us to conduct testing, but we will likely address that in a separate pull request, as we will need to refactor several components to make that happen.

**Comment by VoidRB** [comment]
cool, also gotta add the whole WebSocket side of it all, and today i tried to contact the server through the client using CORS and it didn't work so gotta figure that out now....

**Comment by VoidRB** [comment]
had a bunch ot tweaks and stuff done, tried to had git hooks, commited but then needed to fix a hook, did ` git reset --hard ` and lost all of the progress lol

**Comment by phr3nzy** [comment]
Using husky?

**Comment by phr3nzy** [comment]
Commits don't need to have a ton of functionality. It's actually best to keep commits small and lean in terms of code. Think of it like a checkpoint, you want to save your progress often

**Comment by VoidRB** [comment]
> Using husky?

nah theres this way through a deno pkg, same logic as husky, fixed all the work but now i gotta do it again -.-

**Comment by VoidRB** [comment]
btw i saw you refactored the messages service into a more "defined" way with zod and stuff, should i do the same for the rest?

**Comment by phr3nzy** [comment]
Yeah, let's also try to keep the models colocated with the service

**Comment by VoidRB** [comment]
and the rest of the methods(all the message and session and users related ones's) refactor them as well?

**Comment by phr3nzy** [comment]
> and the rest of the methods(all the message and session and users related ones's) refactor them as well?

yep, welcome to software..

**Comment by VoidRB** [comment]
is there a reason to have THIS much safety in this case? i thought TS would be enough

**Comment by phr3nzy** [comment]
TS only gives you a hint as to what the type of something might be. In the end, TypeScript is compiled to JavaScript and if you don't actually have guards in place you'll run into runtime errors.

For example:
```typescript
export async function createMeasurement(req: Request, res: Response) {
  const celsiusTemperature = req.body.temperature as number;
  
  const kelvinTemperature = celsiusTemperature + 237.15;
  
  await db.measurements.create({
    temperature: kelvinTemperature,
    timestamp: Date.now(),
  });
}
```

So in this example, the temperature is inferred as a number by typescript, all is well and dandy. But you could have a client that sends strings instead of numbers; you're not _actually_ verifying the type during the runtime so it might as well be anything.

TypeScript is what we call syntactic sugar; it's more of a glaze on top and is always harmful by itself; you need to augment it with so much to actually benefit from it.

**Comment by phr3nzy** [comment]
That's why we need to validate things during runtime. And that's just the start.

**Comment by VoidRB** [comment]
ahaaaa okay, so since this "project" is going to be stateful we're making sure that all data moving is correct and accurate in its forms and such

**Comment by phr3nzy** [comment]
Yes, but in any situation where you're taking an input, you want to verify that that's what you're actually getting, or sending an error response back if it's not what you're getting.

**Comment by phr3nzy** [comment]
If you're taking an object or array, you'd want to verify the shape and each of its contents. If it's a file, there are ways to also verify the type of file, etc.

**Comment by VoidRB** [comment]
finally finished it all and registering and logging in works and both make sessions, but the part where we need to store them client side is still not implemented.

what next chief?

**Pull request merged**
