### PR TITLE
feat: added prisma and used std lib

### PR DESCRIPTION
**Pull request by phr3nzy**
TODO:
- fix and get everything running
- write unit and integration tests
- improve routing by splitting CRUD into http and messaging into websockets
- use github workflows to run tests

### CODE REVIEW

**Comment by VoidRB** [comment]
ahh yes, all seem doable but the prisma engine problem persists, tried various ways to try and progress but then another error pops up about some "set-blocking" package containing an error

**Comment by phr3nzy** [comment]
what do you think we have as options? we can remove prisma and replace it with either raw sql, although i wont recommend doing it, or maybe an orm?

**Comment by VoidRB** [comment]
well, i wanted to see if its a problem with deno or the structure of it all, but so far its complying with the docs in terms of setup

**Comment by VoidRB** [comment]
seems like deno and prisma dont like eachother that much (from what i found), tried to copy the copy into another "space" without all the extra stuff but still same problem, going to switch back to node and refactor what needs factoring

**Comment by phr3nzy** [comment]
No, keep deno, it's decent. Change prisma

**Comment by phr3nzy** [comment]
See what's out there in the std library of deno vs. existing libraries for deno, look up pros and cons and decide which to use (std vs. lib)

**Comment by phr3nzy** [comment]
You most likely won't find the pros and cons right out the gate, but ignore any related to performance and security for now

**Comment by VoidRB** [comment]
will do, tried to refactor this morning with node and it was a ball of S*** on fire so deno it is ;p

**Comment by VoidRB** [comment]
UPDATE : so far i've refactored everything except the services, been looking at three ORMs/packages and i haven't decided yet but will do today.

**Pull request closed without merging**
